################
### MONITORS ###
################

# integrated
monitor=eDP-1,preferred,0x0,1.3333 

# Computer Lab
monitor=desc:Dell Inc. DELL U2724DE 6WHM8P3, preferred, 1692x0, 1

monitor=desc:AOC U27B3A ZXLR3HA001353, preferred, 1692x0, 1.5

monitor= , preferred, auto, 1

